In [74]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.offline as pyo

In [75]:
matches=pd.read_csv('matches.csv')
delivery=pd.read_csv('deliveries.csv')
ipl=delivery.merge(matches,left_on='match_id',right_on='id')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

In [76]:
#scatter plots
#problem :- we are going to draw a scatter plot between batsman avg (x-axis) and 
# batsman strike rate on y asix of top 50 batsman in ipl all time

In [77]:
#avg vs sr graph of top 50 batsman (in term of total runs)

top50=ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(50).index.tolist()
new_ipl=ipl[ipl['batsman'].isin(top50)]

In [78]:
#calculating sr
runs=new_ipl.groupby('batsman')['batsman_runs'].sum()
balls=new_ipl.groupby('batsman')['batsman_runs'].count()
sr=(runs/balls)*100
sr=sr.reset_index()
sr

             batsman  batsman_runs
0     AB de Villiers    145.129059
1       AC Gilchrist    133.054662
2           AJ Finch    126.299213
3          AM Rahane    117.486549
4          AT Rayudu    123.014257
5        BB McCullum    126.318203
6           BJ Hodge    121.422376
7           CH Gayle    144.194313
8          DA Miller    137.709251
9          DA Warner    138.318401
10          DJ Bravo    122.286822
11         DJ Hussey    120.072661
12  DPMD Jayawardene    118.791064
13          DR Smith    132.279534
14      F du Plessis    124.161074
15         G Gambhir    120.361200
16        GJ Maxwell    157.564103
17         JH Kallis    105.936272
18         JP Duminy    121.970624
19        KA Pollard    140.621266
20     KC Sangakkara    118.469101
21        KD Karthik    123.008475
22           KK Nair    124.650161
23           M Vijay    120.028681
24        MEK Hussey    119.963592
25         MK Pandey    116.938453
26         MK Tiwary    114.127424
27          MS Dhoni    132.835821
28           NV Ojha    114.528024
29          PA Patel    112.718447
30          R Dravid    113.347237
31         RA Jadeja    118.792867
32         RG Sharma    128.497251
33        RV Uthappa    127.635135
34       S Badrinath    115.742972
35          S Dhawan    118.502496
36        SC Ganguly    101.734540
37          SE Marsh    130.109775
38          SK Raina    134.995548
39         SPD Smith    128.507127
40      SR Tendulkar    114.187867
41         SR Watson    134.838379
42         SS Tiwary    114.851485
43         SV Samson    122.403433
44        TM Dilshan    110.124164
45           V Kohli    126.588437
46          V Sehwag    148.827059
47           WP Saha    127.727646
48         YK Pathan    140.751445
49      Yuvraj Singh    126.390244

In [79]:
#calculating avg
#avg=(total number of runs)/(number of outs)
out=ipl[ipl['player_dismissed'].isin (top50)]
nout=out['player_dismissed'].value_counts()
avg=runs/nout
avg=avg.reset_index()
avg

             batsman          0
0     AB de Villiers  38.307692
1       AC Gilchrist  27.223684
2           AJ Finch  27.186441
3          AM Rahane  33.593407
4          AT Rayudu  27.146067
5        BB McCullum  28.112245
6           BJ Hodge  33.333333
7           CH Gayle  41.022472
8          DA Miller  34.733333
9          DA Warner  40.140000
10          DJ Bravo  22.945455
11         DJ Hussey  26.979592
12  DPMD Jayawardene  28.250000
13          DR Smith  28.392857
14      F du Plessis  30.116279
15         G Gambhir  31.541985
16        GJ Maxwell  25.081633
17         JH Kallis  28.552941
18         JP Duminy  39.860000
19        KA Pollard  28.707317
20     KC Sangakkara  25.953846
21        KD Karthik  24.811966
22           KK Nair  25.173913
23           M Vijay  26.431579
24        MEK Hussey  38.764706
25         MK Pandey  28.500000
26         MK Tiwary  29.428571
27          MS Dhoni  37.872340
28           NV Ojha  20.986486
29          PA Patel  21.700935
30          R Dravid  28.233766
31         RA Jadeja  24.055556
32         RG Sharma  32.612403
33        RV Uthappa  29.515625
34       S Badrinath  30.659574
35          S Dhawan  32.669725
36        SC Ganguly  25.452830
37          SE Marsh  39.507937
38          SK Raina  33.940299
39         SPD Smith  37.239130
40      SR Tendulkar  33.826087
41         SR Watson  30.917647
42         SS Tiwary  28.355556
43         SV Samson  25.464286
44        TM Dilshan  26.813953
45           V Kohli  37.483051
46          V Sehwag  27.555556
47           WP Saha  25.524590
48         YK Pathan  29.816327
49      Yuvraj Singh  25.653465

In [80]:
df=avg.merge(sr,on='batsman')
df.rename(columns={0:'avg','batsman_runs':'sr'},inplace=True)
df

             batsman        avg          sr
0     AB de Villiers  38.307692  145.129059
1       AC Gilchrist  27.223684  133.054662
2           AJ Finch  27.186441  126.299213
3          AM Rahane  33.593407  117.486549
4          AT Rayudu  27.146067  123.014257
5        BB McCullum  28.112245  126.318203
6           BJ Hodge  33.333333  121.422376
7           CH Gayle  41.022472  144.194313
8          DA Miller  34.733333  137.709251
9          DA Warner  40.140000  138.318401
10          DJ Bravo  22.945455  122.286822
11         DJ Hussey  26.979592  120.072661
12  DPMD Jayawardene  28.250000  118.791064
13          DR Smith  28.392857  132.279534
14      F du Plessis  30.116279  124.161074
15         G Gambhir  31.541985  120.361200
16        GJ Maxwell  25.081633  157.564103
17         JH Kallis  28.552941  105.936272
18         JP Duminy  39.860000  121.970624
19        KA Pollard  28.707317  140.621266
20     KC Sangakkara  25.953846  118.469101
21        KD Karthik  24.811966  123.008475
22           KK Nair  25.173913  124.650161
23           M Vijay  26.431579  120.028681
24        MEK Hussey  38.764706  119.963592
25         MK Pandey  28.500000  116.938453
26         MK Tiwary  29.428571  114.127424
27          MS Dhoni  37.872340  132.835821
28           NV Ojha  20.986486  114.528024
29          PA Patel  21.700935  112.718447
30          R Dravid  28.233766  113.347237
31         RA Jadeja  24.055556  118.792867
32         RG Sharma  32.612403  128.497251
33        RV Uthappa  29.515625  127.635135
34       S Badrinath  30.659574  115.742972
35          S Dhawan  32.669725  118.502496
36        SC Ganguly  25.452830  101.734540
37          SE Marsh  39.507937  130.109775
38          SK Raina  33.940299  134.995548
39         SPD Smith  37.239130  128.507127
40      SR Tendulkar  33.826087  114.187867
41         SR Watson  30.917647  134.838379
42         SS Tiwary  28.355556  114.851485
43         SV Samson  25.464286  122.403433
44        TM Dilshan  26.813953  110.124164
45           V Kohli  37.483051  126.588437
46          V Sehwag  27.555556  148.827059
47           WP Saha  25.524590  127.727646
48         YK Pathan  29.816327  140.751445
49      Yuvraj Singh  25.653465  126.390244

In [81]:
#scatter plot

trace=go.Scatter(x=df['avg'],y=df['sr'],mode='markers',hovertext=df['batsman'],marker={'color':'#00a65a'})
data=[trace]
layout=go.Layout(title='batsman Avg vs sr',xaxis={'title':'Avg'},yaxis={'title':'sr'})
fig=go.Figure(data=data,layout=layout)
#pyo.plot(fig) #show in server
fig.show()

In [82]:
trace=go.Scatter(x=df['avg'],y=df['sr'],mode='markers',hovertext=df['batsman'],marker={'color':'#00a65a','size':16})
data=[trace]
layout=go.Layout(title='batsman Avg vs sr',xaxis={'title':'Avg'},yaxis={'title':'sr'})
fig=go.Figure(data=data,layout=layout)
fig.show()

In [83]:
trace=go.Scatter(x=df['avg'],y=df['sr'],mode='markers',hovertext=df['batsman'],marker={'color':'#00a65a','size':15})
data=[trace]
layout=go.Layout(title='batsman Avg vs sr',xaxis={'title':'Avg'},yaxis={'title':'sr'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig,filename='myfile.html')

'myfile.html'

### Line chart

In [84]:
ipl.sample()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
15432,66,2,Delhi Daredevils,Deccan Chargers,5,6,V Sehwag,S Dhawan,WPUJC Vaas,0,...,normal,0,Delhi Daredevils,0,9,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",IL Howell,AM Saheba,NaN

In [85]:
# year by year performance batsman 
single=ipl[ipl['batsman']=='V Kohli']
performance=single.groupby('season')['batsman_runs'].sum().reset_index()
performance

   season  batsman_runs
0    2008           165
1    2009           246
2    2010           307
3    2011           557
4    2012           364
5    2013           639
6    2014           359
7    2015           505
8    2016           973
9    2017           308

In [86]:
trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],mode='lines',marker={'color':'#00a65a'})
data=[trace]
layout=go.Layout(title='year by year performance',xaxis={'title':'season'},yaxis={'title':'performance'})
fig=go.Figure(data=data,layout=layout)
fig.show()

In [87]:
trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],mode='lines+markers',marker={'color':'#00a65a'})
data=[trace]
layout=go.Layout(title='year by year performance',xaxis={'title':'season'},yaxis={'title':'performance'})
fig=go.Figure(data=data,layout=layout)
fig.show()

In [91]:
single1=ipl[ipl['batsman']=='MS Dhoni']
performance1=single1.groupby('season')['batsman_runs'].sum().reset_index()
performance1

   season  batsman_runs
0    2008           414
1    2009           332
2    2010           287
3    2011           392
4    2012           357
5    2013           461
6    2014           371
7    2015           372
8    2016           284
9    2017           290

In [95]:
trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],mode='lines+markers',marker={'color':'#00a65a'},name='Virat Kohli')

trace1=go.Scatter(x=performance1['season'],y=performance1['batsman_runs'],mode='lines+markers',marker={'color':"#0011a6"},name='MS Dhoni')

data=[trace,trace1]
layout=go.Layout(title='year by year performance',xaxis={'title':'season'},yaxis={'title':'performance'})
fig=go.Figure(data=data,layout=layout)
fig.show()