Pandas groupby()

Basic syntax

df.groupby(by, axis=0, level=None, as_index=True, sort=True,group_keys=True, observed=True, dropna=True)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame({
     'Department':['IT','HR','IT','HR','Sales'],
     'salary':[50000,40000,60000,45000,55000]
})
df

  Department  salary
0         IT   50000
1         HR   40000
2         IT   60000
3         HR   45000
4      Sales   55000

In [3]:
group=df.groupby('Department')
type(group)

pandas.api.typing.DataFrameGroupBy

Why doesn't groupby() itself give the result?
:-groupby() only performs the split part.

In [4]:
df.groupby('Department')['salary'].mean()

Department
HR       42500.0
IT       55000.0
Sales    55000.0
Name: salary, dtype: float64

Split → Apply → Combine

groupby() + aggregation

In [5]:
df.groupby('Department')['salary'].sum()

Department
HR        85000
IT       110000
Sales     55000
Name: salary, dtype: int64

In [6]:
df.groupby('Department')['salary'].min()

Department
HR       40000
IT       50000
Sales    55000
Name: salary, dtype: int64

Important difference: count() vs size()
count() counts non-missing values.
size() counts rows, including rows containing NaN.

In [7]:
df.groupby('Department')['salary'].count()

Department
HR       2
IT       2
Sales    1
Name: salary, dtype: int64

In [8]:
df.groupby('Department')['salary'].size()

Department
HR       2
IT       2
Sales    1
Name: salary, dtype: int64

In [9]:
diabetes=pd.read_csv('diabetes.csv')
diabetes.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [10]:
diabetes.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [11]:
ipl=pd.read_csv('ipl-matches.csv')
ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [12]:
ipl.isna().sum()

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [13]:
ipl.groupby('Season')['City'].count()

Season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       47
2015       59
2016       60
2017       59
2018       60
2019       60
2020/21    22
2021       60
2022       74
Name: City, dtype: int64

In [14]:
ipl.groupby('Season')['City'].size()

Season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       60
2015       59
2016       60
2017       59
2018       60
2019       60
2020/21    60
2021       60
2022       74
Name: City, dtype: int64

Multiple aggregations

In [15]:
df.groupby('Department')['salary'].agg(['mean', 'max', 'min', 'sum'])

               mean    max    min     sum
Department
HR          42500.0  45000  40000   85000
IT          55000.0  60000  50000  110000
Sales       55000.0  55000  55000   55000

In [16]:
ipl.groupby('Season')['Margin'].agg(['mean', 'max', 'min', 'sum'])

              mean    max  min     sum
Season
2007/08  15.965517  140.0  1.0   926.0
2009     16.857143   92.0  1.0   944.0
2009/10  19.762712   98.0  2.0  1166.0
2011     18.930556  111.0  2.0  1363.0
2012     16.229730   86.0  1.0  1201.0
2013     19.837838  130.0  2.0  1468.0
2014     14.728814   93.0  2.0   869.0
2015     17.821429  138.0  1.0   998.0
2016     15.333333  144.0  1.0   920.0
2017     17.103448  146.0  1.0   992.0
2018     14.350000  102.0  1.0   861.0
2019     15.210526  118.0  1.0   867.0
2020/21  22.589286   97.0  2.0  1265.0
2021     13.576271   86.0  1.0   801.0
2022     16.972973   91.0  2.0  1256.0

Different functions for different columns

In [17]:
df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR'],
    'Salary': [50000, 60000, 40000, 45000],
    'Age': [25, 30, 28, 35]
})
df

  Department  Salary  Age
0         IT   50000   25
1         IT   60000   30
2         HR   40000   28
3         HR   45000   35

In [18]:
df.groupby('Department').agg({
    'Salary': 'mean',
    'Age': 'max'
})

             Salary  Age
Department
HR          42500.0   35
IT          55000.0   30

In [19]:
diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [20]:
diabetes.groupby('Pregnancies').agg({
   'Glucose':'mean',
   'BloodPressure' :'min' ,
   'SkinThickness':'max'
})

                Glucose  BloodPressure  SkinThickness
Pregnancies
0            123.000000              0             63
1            112.748148              0             52
2            110.796117              0             99
3            123.586667              0             49
4            125.117647              0             47
5            118.859649             48             44
6            120.800000              0             45
7            136.444444              0             49
8            131.736842              0             46
9            131.392857             52             46
10           120.916667              0             48
11           126.454545              0             40
12           113.555556             62             43
13           125.500000              0             54
14           137.500000             62             30
15           136.000000             70             32
17           163.000000             72             41

In [21]:
diabetes.groupby('Pregnancies').agg({
   'Glucose':'mean',
   'BloodPressure' :['min','max'] ,
   'SkinThickness':'max'
})

                Glucose BloodPressure      SkinThickness
                   mean           min  max           max
Pregnancies
0            123.000000             0  110            63
1            112.748148             0  122            52
2            110.796117             0   96            99
3            123.586667             0  100            49
4            125.117647             0  110            47
5            118.859649            48  108            44
6            120.800000             0   96            45
7            136.444444             0   95            49
8            131.736842             0  106            46
9            131.392857            52  110            46
10           120.916667             0  106            48
11           126.454545             0  106            40
12           113.555556            62   85            43
13           125.500000             0  114            54
14           137.500000            62   78            30
15           136.000000            70   70            32
17           163.000000            72   72            41

Named aggregation

In [22]:
df.groupby('Department').agg(
    average_salary=('Salary', 'mean'),
    maximum_age=('Age', 'max')
)

            average_salary  maximum_age
Department
HR                 42500.0           35
IT                 55000.0           30

In [23]:
ipl.groupby('Season').agg(
     mean_margin=('Margin','mean')
)

         mean_margin
Season
2007/08    15.965517
2009       16.857143
2009/10    19.762712
2011       18.930556
2012       16.229730
2013       19.837838
2014       14.728814
2015       17.821429
2016       15.333333
2017       17.103448
2018       14.350000
2019       15.210526
2020/21    22.589286
2021       13.576271
2022       16.972973

Grouping by multiple columns

In [24]:
df = pd.DataFrame({
    'Department': ['IT', 'IT', 'IT', 'HR', 'HR'],
    'Gender': ['M', 'F', 'M', 'F', 'M'],
    'Salary': [50000, 60000, 55000, 40000, 45000]
})
df

  Department Gender  Salary
0         IT      M   50000
1         IT      F   60000
2         IT      M   55000
3         HR      F   40000
4         HR      M   45000

In [25]:
df.groupby(['Department', 'Gender'])['Salary'].mean()

Department  Gender
HR          F         40000.0
            M         45000.0
IT          F         60000.0
            M         52500.0
Name: Salary, dtype: float64

as_index

In [26]:
df.groupby('Department')['Salary'].mean()

Department
HR    42500.0
IT    55000.0
Name: Salary, dtype: float64

In [27]:
df.groupby('Department', as_index=False)['Salary'].mean()

  Department   Salary
0         HR  42500.0
1         IT  55000.0

sort

In [28]:
df.groupby('Department', sort=False)['Salary'].mean()

Department
IT    55000.0
HR    42500.0
Name: Salary, dtype: float64

In [29]:
df.groupby('Department',sort=False)['Salary'].mean().sort_values()

Department
HR    42500.0
IT    55000.0
Name: Salary, dtype: float64

In [30]:
type(df.groupby('Department')[['Salary']].mean())

pandas.DataFrame

In [31]:
df.groupby('Department')['Salary'].idxmax()

Department
HR    4
IT    1
Name: Salary, dtype: int64

In [32]:
df.loc[df.groupby('Department')['Salary'].idxmax()]

  Department Gender  Salary
4         HR      M   45000
1         IT      F   60000

transform() with groupby()

In [33]:
df['dept_mean'] = (
    df.groupby('Department')['Salary'].transform('mean')
)
df

  Department Gender  Salary  dept_mean
0         IT      M   50000    55000.0
1         IT      F   60000    55000.0
2         IT      M   55000    55000.0
3         HR      F   40000    42500.0
4         HR      M   45000    42500.0

filter()
filter() allows you to keep or remove entire groups based on a condition.

In [34]:
df.groupby('Department').filter(
    lambda x: len(x) >= 2
)

  Department Gender  Salary  dept_mean
0         IT      M   50000    55000.0
1         IT      F   60000    55000.0
2         IT      M   55000    55000.0
3         HR      F   40000    42500.0
4         HR      M   45000    42500.0

apply()

In [35]:
def highest_salary(group):
    return group.loc[group['Salary'].idxmax()]

df.groupby('Department').apply(highest_salary)

           Gender  Salary  dept_mean
Department
HR              M   45000    42500.0
IT              F   60000    55000.0

Iterating over groups

In [36]:
for name, group in df.groupby('Department'):
    print(name)
    print(group)

HR
  Department Gender  Salary  dept_mean
3         HR      F   40000    42500.0
4         HR      M   45000    42500.0
IT
  Department Gender  Salary  dept_mean
0         IT      M   50000    55000.0
1         IT      F   60000    55000.0
2         IT      M   55000    55000.0

get_group()

In [37]:
grouped = df.groupby('Department')
grouped.get_group('IT')

  Department Gender  Salary  dept_mean
0         IT      M   50000    55000.0
1         IT      F   60000    55000.0
2         IT      M   55000    55000.0

Missing values and dropna

In [38]:
df.groupby('Department', dropna=False).size()

Department
HR    2
IT    3
dtype: int64

In [39]:
df.groupby('Department').size()

Department
HR    2
IT    3
dtype: int64